FROM debian:stretch-slim

MAINTAINER spencer@somanydoors.ca

RUN apt-get -qq update && \
	apt-get -qq install \
		mariadb-client \
		mariadb-server \
		php7.0 \
		php7.0-mysql \
		apache2 \
		libapache2-mod-php7.0 \
		php7.0-xml \
		php7.0-gd \
		php7.0-mbstring \
		php7.0-zip \
		php7.0-bz2 \
		php7.0-curl \
		php7.0-intl \
		php7.0-mcrypt \
		php7.0-ldap \
		php-smbclient \
		php7.0-imap \
		php7.0-gmp \
		php-apcu \
		php-imagick \
		ffmpeg